service: simple-dynamic-webpage

provider:
  name: aws
  runtime: nodejs8.10

functions:
  homepage:
    handler: controller/homeController.home
    events:
      - http:
          method: GET
          path: '/'

custom:
  serverless-offline:
    port: 4000

plugins:
  - serverless-offline