service: a-simple-service

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: '/'
          method: GET

  myfunction:
    handler: another-handler.myexample
    events:
      - http:
          path: '/myAPI/{mypath1}/{mypath2}'
          method: GET
  
  appendExtension:
    handler: another-handler.appendExtension 
    events: 
      - http:
          path: '/append/{extension}'
          method: POST

plugins:
  - serverless-offline
  
